# Generated by Django 3.1.7 on 2021-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='deadplayers',
            new_name='deadPlayers',
        ),
        migrations.AlterField(
            model_name='game',
            name='days',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.TextField(default='[]'),
        ),
    ]
