# Generated by Django 3.1.7 on 2021-04-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorderapp', '0002_auto_20210425_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='eventid',
            new_name='eventId',
        ),
    ]
