# Generated by Django 3.1.7 on 2021-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorderapp', '0004_auto_20210426_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='dayId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='frameId',
            field=models.IntegerField(default=0),
        ),
    ]
